### ISSUE TITLE
Int Overflow Bug Reoccurs - Please Add Better Testing

### ISSUE THREAD

**Issue by bonedaddy** [dgraph-io/badger#1182]
This is the second time in less than two months that an issue with integer overflow happens, breaking builds on 32-bit platforms.  Given that this is the second occurrence of such a bug, I think testing needs to be improved to catch this, because if it has already happened twice in 2 months, it will probably happen a 3rd, and a 4th if testing isn't improved to catch this.

Previous bug report https://github.com/dgraph-io/badger/issues/1142, commit fixing the first time the bug happened https://github.com/dgraph-io/badger/commit/fb0cdb858c78004b9db8f08e91bb713780b20445, and the most recent commit to fix the same issue https://github.com/dgraph-io/badger/commit/465f28aba5fee9a4dac132ccbebaaae6a1d711dd

**Comment by jarifibrahim** [comment]
Thanks @bonedaddy . We should be able to add build options for 32-bit platforms to our travis.yml file

**Comment by bonedaddy** [comment]
@jarifibrahim could also that a look at https://github.com/mitchellh/gox it's how I handle this stuff and its been working pretty well.

**Comment by jarifibrahim** [comment]
@bonedaddy https://github.com/mitchellh/gox looks great but I think it might an overkill for us. I think if we just add a `GOARCH=386 go build` it should be enough :)

**Comment by anjannath** [comment]
@jarifibrahim So no need to add unit tests, just a build on i386 platform is enough for the test?

**Comment by jarifibrahim** [comment]
Yes. Adding a `GOARCH=386 go build` would ensure we don't break badger for 32-bit platforms.

**Comment by andhe** [comment]
I've uploaded badger to Debian a while ago, which means it gets built on a number of different architectures. Full logs available here (click red/green status column for full build logs):
https://buildd.debian.org/status/package.php?p=badger

As can be seen by cherry-picking the already committed fix, badger builds on 32bit architectures but testsuite has multiple failures and even crashes and even compilation failures. Maybe it's just the test-suite being broken and badger actually works on 32bit, but I'm scared to just disable the testsuite on all 32bit archs. Would be great if the test-suite also worked on 32 bit archs, so actually running it in your CI would IMHO be nice.


Here are three examples of failures:

```
src/github.com/dgraph-io/badger/db2_test.go:313:14: len argument too large in make([]byte)

$ cat -n db2_test.go  | grep '^ *313'
   313					v := make([]byte, 2<<30)
```
```
=== RUN   TestRotate
badger 2020/02/03 12:04:18 INFO: All 0 tables opened in 0s
badger 2020/02/03 12:04:19 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
badger 2020/02/03 12:04:19 INFO: All 0 tables opened in 0s
badger 2020/02/03 12:04:19 INFO: Replaying file id: 0 at offset: 0
badger 2020/02/03 12:04:19 INFO: Replay took: 16.72µs
--- FAIL: TestRotate (1.16s)
    rotate_test.go:53: 
        	Error Trace:	rotate_test.go:53
        	Error:      	Received unexpected error:
        	            	Map log file. Path=/tmp/badger-test546655184/000000.vlog. Error=cannot allocate memory
        	            	During db.vlog.open
        	            	github.com/dgraph-io/badger/y.Wrapf
        	            		/home/ah/badger-2.0.1/obj-arm-linux-gnueabi/src/github.com/dgraph-io/badger/y/error.go:82
        	            	github.com/dgraph-io/badger.Open
        	            		/home/ah/badger-2.0.1/obj-arm-linux-gnueabi/src/github.com/dgraph-io/badger/db.go:357
        	            	github.com/dgraph-io/badger/badger/cmd.TestRotate
        	            		/home/ah/badger-2.0.1/obj-arm-linux-gnueabi/src/github.com/dgraph-io/badger/badger/cmd/rotate_test.go:52
        	            	testing.tRunner
        	            		/usr/lib/go-1.13/src/testing/testing.go:909
        	            	runtime.goexit
        	            		/usr/lib/go-1.13/src/runtime/asm_arm.s:868
        	Test:       	TestRotate
FAIL
```


```
=== RUN   TestTableIndex/multiple_keys
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x39b050]

goroutine 9 [running]:
testing.tRunner.func1(0x20b2280)
	/usr/lib/go-1.13/src/testing/testing.go:874 +0x360
panic(0x3f7dc8, 0x744668)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x194
github.com/dgraph-io/badger/table.(*Table).KeyID(...)
	/home/ah/badger-2.0.1/obj-arm-linux-gnueabi/src/github.com/dgraph-io/badger/table/table.go:500
github.com/dgraph-io/badger/table.TestTableIndex.func2(0x20b2280)
	/home/ah/badger-2.0.1/obj-arm-linux-gnueabi/src/github.com/dgraph-io/badger/table/builder_test.go:85 +0xaac
testing.tRunner(0x20b2280, 0x467044)
	/usr/lib/go-1.13/src/testing/testing.go:909 +0xa8
created by testing.(*T).Run
	/usr/lib/go-1.13/src/testing/testing.go:960 +0x2ac
FAIL	github.com/dgraph-io/badger/table	0.290s
```
(FWIW, I guess the last one crashes because the tbl is dereferenced before `require.NoError(t, err, "unable to open table")` is used and OpenTable probably failed for some reason leaving `tbl==nil`. )

**Comment by andhe** [comment]
I've created a patch that seems to make everything build and testsuite pass for me on (atleast) 32bit (arm).
See: https://salsa.debian.org/go-team/packages/badger/blob/master/debian/patches/fix-32bit.patch

Please scream at me if I'm messing something up in badger with my changes. Please feel free to apply my patch (as I don't think it reaches https://en.wikipedia.org/wiki/Threshold_of_originality so no copyright).

**Comment by luca-moser** [comment]
Any updates on this? Version v2.0.1 can not be compiled on 32 bit systems.

**Comment by jarifibrahim** [comment]
@vardhanapoorv ^^

**Comment by jarifibrahim** [comment]
Hey @bonedaddy and @luca-moser, I've merged the fix for this issue https://github.com/dgraph-io/badger/pull/1216. Hopefully, the 32-bit overflow issue won't reappear :)

**Comment by andhe** [comment]
Hi @jarifibrahim, sorry for not finding the time to get back to you earlier. I just wanted to report back that I've uploaded badger 2.0.2 to Debian (with all my previous local patches dropped) and the test suite doesn't pass (failing the Debian build).

For full build/test logs click the red box at https://buildd.debian.org/status/package.php?p=badger

My previous patches that actually both built and passed the testsuite on 32bit can be found at https://sources.debian.org/src/badger/2.0.1-4/debian/patches/

Note however that it seems like badger will still not actually be usable on 32bit because your allocating all free memory space when running badger standalone, means that when an application that includes badger does a single memory allocation before initializing badger means there's not enough memory space for badger anymore. (At least that's my guess, I haven't really found time to look closer at this.)

I spent a few minutes on trying to get garagemq (which uses badger) to work on 32bit but quickly gave up... My comments for that are at https://github.com/valinurovam/garagemq/issues/26#issuecomment-581894178

**Comment by jarifibrahim** [comment]
Hey @andhe I see 
```
/<<PKGBUILDDIR>>/obj-powerpc64-linux-gnu/src/github.com/dgraph-io/badger/skl/skl.go:170: error: undefined reference to 'github.com..z2fdgraph..z2dio..z2fristretto..z2fz.FastRand'
```
on https://buildd.debian.org/status/package.php?p=badger .

What version of go are you using? I've seen the `missing fastrand` issue on go 1.10 and befow.

`fastrand` is loaded from the standard go libray.

**Comment by jarifibrahim** [comment]
>Note however that it seems like badger will still not actually be usable on 32bit because your allocating all free memory space when running badger standalone, means that when an application that includes badger does a single memory allocation before initializing badger means there's not enough memory space for badger anymore. (At least that's my guess, I haven't really found time to look closer at this.)

I don't think I understand this correctly. Why does the application which uses badger consume all the memory?

**Comment by gonzojive** [comment]
I think this bug is back again:

./../go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:50:5: constant 4294967295 overflows int
